
skillMetadata:
  sections:
    - name: Title
      fields:
        - name: title
        - type: text
        - label: Please choose how I should address you
        - value: empty
    - name: Language
      fields:
        - name: language
        - type: text
        - label: Please choose a language
        - value: empty